// const AObject = node.getObjectByName('flexbeamstroke_hydraulic_fixed_pos')
// const BObject = node.getObjectByName('flexbeamstroke_hydraulic_fixed_end')
// const CObject = node.getObjectByName('flexbeamstroke_hydraulic_slidingshaft_pos')
// const DObject = node.getObjectByName('frontdisstart1')
// const EObject = node.getObjectByName('flexbeamstroke_pos')
// AObject.lookAt(BObject.getWorldPosition(new THREE.Vector3()))
// BObject.lookAt(AObject.getWorldPosition(new THREE.Vector3()))
// CObject.lookAt(BObject.getWorldPosition(new THREE.Vector3()))
// aa.lookAt(bb.getWorldPosition(new THREE.Vector3()))
// bb.lookAt(CObject.getWorldPosition(new THREE.Vector3()))

const AObject = node.getObjectByName('flexbeamstroke_hydraulic_fixed_pos')
const BObject = node.getObjectByName('flexbeamstroke_hydraulic_fixed_end')
const CObject = node.getObjectByName('flexbeamstroke_hydraulic_slidingshaft_pos')
const DObject = node.getObjectByName('frontdisstart1')
const EObject = node.getObjectByName('flexbeamstroke_pos')
AObject.lookAt(BObject.getWorldPosition(new THREE.Vector3()))
BObject.lookAt(AObject.getWorldPosition(new THREE.Vector3()))
CObject.lookAt(BObject.getWorldPosition(new THREE.Vector3()))
DObject.lookAt(EObject.getWorldPosition(new THREE.Vector3()))
EObject.lookAt(CObject.getWorldPosition(new THREE.Vector3()))
